/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AccountantRole;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import Business.Employee.Employee;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.ProjectApprovalRole.ProjectApprovalJPanel;

/**
 *
 * @author xinzh
 */
public class AccountantWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Organization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Network network;
    private Employee employee;
    
    public AccountantWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, Network network, Employee employee) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.network = network;
        this.employee = employee;
        valueLabel.setText(enterprise.getName());
        valueLabel1.setText(employee.getName());
        populateRequestTable();
        populateCompleteTable();
         SectorJComboBox.removeAllItems();
         SectorJComboBox.addItem(Organization.Type.Charity);
         SectorJComboBox.addItem(Organization.Type.Commercial);
         SectorJComboBox1.removeAllItems();
         SectorJComboBox1.addItem(Organization.Type.Charity);
         SectorJComboBox1.addItem(Organization.Type.Commercial);
    }
    public void populateRequestTable(){
           
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();   
        model.setRowCount(0);
        for (WorkRequest request : network.getProjectList().getWorkRequestList()){
            if(request.getStatus().equals("Fullfilled")){
            Object[] row = new Object[5];
            row[0] = request;
            row[1] = request.getRequestFunds();
            row[2] = request.getRecievedFunds();
            row[3] = request.getSector();
            row[4] = request.getStatus();
            
            model.addRow(row);}
        }
}
public void populateCompleteTable(){
        DefaultTableModel model = (DefaultTableModel) CompletedProjectsJTable1.getModel();   
        model.setRowCount(0);
        for (WorkRequest request : network.getProjectList().getWorkRequestList()){
            if(request.getStatus().equals("Completed")){
            Object[] row = new Object[5];
            row[0] = request;
            row[1] = request.getRequestFunds();
            row[2] = request.getRecievedFunds();
            row[3] = request.getSector();
            row[4] = request.getStatus();      
            model.addRow(row);}
}
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        refreshTestJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        enterpriseLabel1 = new javax.swing.JLabel();
        valueLabel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        ReleaseFundsBtn = new javax.swing.JButton();
        SectorJComboBox = new javax.swing.JComboBox();
        ViewBtn1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        CompletedProjectsJTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        SectorJComboBox1 = new javax.swing.JComboBox();
        RefreshBtn2 = new javax.swing.JButton();
        ViewBtn2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(175, 206, 175));

        refreshTestJButton.setBackground(new java.awt.Color(255, 255, 255));
        refreshTestJButton.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        refreshTestJButton.setText("Refresh");
        refreshTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTestJButtonActionPerformed(evt);
            }
        });

        enterpriseLabel.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");

        valueLabel.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        valueLabel.setText("<>");

        enterpriseLabel1.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        enterpriseLabel1.setText("Hello Accountant ");

        valueLabel1.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        valueLabel1.setText("<>");

        jLabel1.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        jLabel1.setText("Sector:");

        workRequestJTable.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Project", "Requested Fund (USD)", "Received Fund (USD)", "Sector", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        ReleaseFundsBtn.setBackground(new java.awt.Color(255, 255, 255));
        ReleaseFundsBtn.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ReleaseFundsBtn.setText("Release Fund");
        ReleaseFundsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReleaseFundsBtnActionPerformed(evt);
            }
        });

        SectorJComboBox.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        SectorJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ViewBtn1.setBackground(new java.awt.Color(255, 255, 255));
        ViewBtn1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ViewBtn1.setText("View Details");
        ViewBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBtn1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setText("Fullfilled Projects:");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setText("Completed Projects:");

        CompletedProjectsJTable1.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        CompletedProjectsJTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Project", "Requested Fund", "ReceivedFunds", "Sector", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(CompletedProjectsJTable1);

        jLabel4.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        jLabel4.setText("Sector:");

        SectorJComboBox1.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        SectorJComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SectorJComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SectorJComboBox1ActionPerformed(evt);
            }
        });

        RefreshBtn2.setBackground(new java.awt.Color(255, 255, 255));
        RefreshBtn2.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        RefreshBtn2.setText("Refresh");
        RefreshBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshBtn2ActionPerformed(evt);
            }
        });

        ViewBtn2.setBackground(new java.awt.Color(255, 255, 255));
        ViewBtn2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ViewBtn2.setText("View Details");
        ViewBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(SectorJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(refreshTestJButton)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(SectorJComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(73, 73, 73)
                                        .addComponent(RefreshBtn2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ViewBtn2))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ViewBtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ReleaseFundsBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(113, 113, 113))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(enterpriseLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(enterpriseLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valueLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(239, 239, 239))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valueLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(SectorJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshTestJButton)
                    .addComponent(ViewBtn1))
                .addGap(18, 18, 18)
                .addComponent(ReleaseFundsBtn)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(SectorJComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RefreshBtn2)
                    .addComponent(ViewBtn2))
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTestJButtonActionPerformed
        Organization.Type chosedSector = (Organization.Type)SectorJComboBox.getSelectedItem();
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();   
        model.setRowCount(0);
        for (WorkRequest request : network.getProjectList().getWorkRequestList()){
            Organization.Type sector=request.getSector();
            if(sector.equals(chosedSector)&&request.getStatus().equals("Fullfilled")){
            Object[] row = new Object[5];
            row[0] = request;
            row[1] = request.getRequestFunds();
            row[2] = request.getRecievedFunds();
            row[3] = request.getSector();
            row[4] = request.getStatus();      
            model.addRow(row);}
        }
    }//GEN-LAST:event_refreshTestJButtonActionPerformed

    private void ReleaseFundsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReleaseFundsBtnActionPerformed
        int selectedRow = workRequestJTable.getSelectedRow();      
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row first");
            return;
        }
        WorkRequest request = (WorkRequest)workRequestJTable.getValueAt(selectedRow, 0);
        request.setStatus("Completed");
        JOptionPane.showMessageDialog(null, "Completed");   
        populateRequestTable();
        populateCompleteTable();
    }//GEN-LAST:event_ReleaseFundsBtnActionPerformed

    private void ViewBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBtn1ActionPerformed
        // TODO add your handling code here:
         int selectedRow = workRequestJTable.getSelectedRow();      
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row first");
            return;
        }
      WorkRequest request = (WorkRequest)workRequestJTable.getValueAt(selectedRow, 0);
      CardLayout layout = (CardLayout) userProcessContainer.getLayout();
      userProcessContainer.add(" FundReleaseJPanel", new  FundReleaseJPanel(userProcessContainer, userAccount,organization,enterprise,network,request) );
      layout.next(userProcessContainer);
    }//GEN-LAST:event_ViewBtn1ActionPerformed

    private void RefreshBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshBtn2ActionPerformed
        // TODO add your handling code here:
        Organization.Type chosedSector = (Organization.Type)SectorJComboBox1.getSelectedItem();
        DefaultTableModel model = (DefaultTableModel) CompletedProjectsJTable1.getModel();   
        model.setRowCount(0);
        for (WorkRequest request : network.getProjectList().getWorkRequestList()){
            Organization.Type sector=request.getSector();
            if(sector.equals(chosedSector)&&request.getStatus().equals("Completed")){
            Object[] row = new Object[5];
            row[0] = request;
            row[1] = request.getRequestFunds();
            row[2] = request.getRecievedFunds();
            row[3] = request.getSector();
            row[4] = request.getStatus();      
            model.addRow(row);}
        }
    }//GEN-LAST:event_RefreshBtn2ActionPerformed

    private void ViewBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBtn2ActionPerformed
        // TODO add your handling code here:
    int selectedRow = CompletedProjectsJTable1.getSelectedRow();      
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row first");
            return;
        }
      WorkRequest request = (WorkRequest)CompletedProjectsJTable1.getValueAt(selectedRow, 0);
      CardLayout layout = (CardLayout) userProcessContainer.getLayout();
      userProcessContainer.add(" FundReleaseJPanel", new  FundReleaseJPanel(userProcessContainer, userAccount,organization,enterprise,network,request) );
      layout.next(userProcessContainer);
    }//GEN-LAST:event_ViewBtn2ActionPerformed

    private void SectorJComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SectorJComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SectorJComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CompletedProjectsJTable1;
    private javax.swing.JButton RefreshBtn2;
    private javax.swing.JButton ReleaseFundsBtn;
    private javax.swing.JComboBox SectorJComboBox;
    private javax.swing.JComboBox SectorJComboBox1;
    private javax.swing.JButton ViewBtn1;
    private javax.swing.JButton ViewBtn2;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton refreshTestJButton;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JLabel valueLabel1;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
